spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${database.password}
    url: ${database.url}
    username: ${database.user}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: ${tomcatServerPort}

logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n'
